import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Script
        id="gtm"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={
          {
            __html:
              `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-PM2SD25G');`
          }
        }
      >
      </Script>

      <Script
        id="faro"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={
          {
            __html: `
            (function () {
              var webSdkScript = document.createElement("script");
            
              webSdkScript.src =
                "https://unpkg.com/@grafana/faro-web-sdk@^1.0.0/dist/bundle/faro-web-sdk.iife.js";
            
              webSdkScript.onload = () => {
                window.GrafanaFaroWebSdk.initializeFaro({
                  url: "https://faro-collector-prod-ap-south-1.grafana.net/collect/22862f9cbea20610940213edd9642e3e",
                  app: {
                    name: "shubham-portfolio",
                    version: "1.0.0",
                    environment: "production",
                  },
                  
                });
            
            
                // Load instrumentations at the onLoad event of the web-SDK and after the above configuration.
                // This is important because we need to ensure that the Web-SDK has been loaded and initialized before we add further instruments!
                var webTracingScript = document.createElement("script");
            
                webTracingScript.src =
                  "https://unpkg.com/@grafana/faro-web-tracing@^1.0.0/dist/bundle/faro-web-tracing.iife.js";
            
                // Initialize, configure (if necessary) and add the the new instrumentation to the already loaded and configured Web-SDK.
                webTracingScript.onload = () => {
                  window.GrafanaFaroWebSdk.faro.instrumentations.add(
                    new window.GrafanaFaroWebTracing.TracingInstrumentation()
                  );
                };
            
                // Append the Web Tracing script script tag to the HTML page
                document.head.appendChild(webTracingScript);
              };
            
              // Append the Web-SDK script script tag to the HTML page
              document.head.appendChild(webSdkScript);
            })();`
          }
        }
      >
      </Script>

      <Script
        id="gtm"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={
          {
            __html:
              `<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PM2SD25G"
              height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`
          }
        }
      >
      </Script>

      <body>
        {children}

      </body>

      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/TextPlugin.min.js"
      />
    </html>
  );
}
